## Conic Optimization using ECOS Python

A conic problem has conic (nonlinear) constraints in addition to linear objective function and
linear constraints. Thus linear optimization is a special case of conic optimization.
ECOS is an open-source solver for computing solutions to conic optimization problems. <br>Its
documentation and source code are available online.<br>
https://www.embotech.com/ECOS<br>
https://github.com/embotech/ecos

### Problem 1:
Write a program to solve a linear optimization problem in 'n' variables. Your program
should ask the user to enter an integer value 'n' when prompted, and solve the
following problem by calling the ECOS library.<br>
$$Minimize: x_1 + 3x_2 + 6x_3 + 10x_4 + ... + (n(n+1)/2)x_n$$
$$subject\ to:$$
$$x_1 + x_2 + ... + x_n >= n/2$$
$$x_1 >= 0$$
$$x_2 >= 0$$
$$...$$
$$x_n >= 0$$

In [1]:
import ecos
import numpy as np
from scipy import sparse

In [2]:
##### Part 1 ####
n=int(input("Enter a positive integer:"))

Enter a positive integer:2


In [3]:
c=np.zeros(n)
g=np.identity(n)
g_up=np.ones((1,n))
G=np.concatenate((g_up,g))
G=-G
G=sparse.csc_matrix(G)
h=np.zeros(n+1)
h[0]=-n/2
print(G)
print(h) 

  (0, 0)	-1.0
  (1, 0)	-1.0
  (0, 1)	-1.0
  (2, 1)	-1.0
[-1.  0.  0.]


In [4]:
for i in range(n):
    c[i]=(i+2)*(i+1)/2
print(c)    
# print(type(G))

[ 1.  3.]


In [5]:
dims={'l':n,'q':[1],'e':0}
# solution = ecos.solve(c,G,h,dims,G,h, max_iters=100000,verbose=True)
solution = ecos.solve(c,G,h,dims, max_iters=100000,verbose=True)


ECOS 2.0.4 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  +1.333e+00  +2.667e+00  +9e+00  6e-01  5e-01  1e+00  3e+00    ---    ---    1  1  - |  -  - 
 1  +9.087e-01  +1.124e+00  +6e-01  3e-02  4e-02  2e-01  3e-01  0.9286  3e-02   1  1  1 |  0  0
 2  +9.975e-01  +1.001e+00  +1e-02  6e-04  6e-04  3e-03  5e-03  0.9830  3e-04   2  2  2 |  0  0
 3  +1.000e+00  +1.000e+00  +1e-04  7e-06  7e-06  3e-05  5e-05  0.9890  1e-04   3  2  2 |  0  0
 4  +1.000e+00  +1.000e+00  +1e-06  7e-08  7e-08  4e-07  6e-07  0.9890  1e-04   6  2  2 |  0  0
 5  +1.000e+00  +1.000e+00  +1e-08  8e-10  8e-10  4e-09  6e-09  0.9890  1e-04   2  1  1 |  0  0
 6  +1.000e+00  +1.000e+00  +2e-10  9e-12  9e-12  5e-11  7e-11  0.9890  1e-04   2  0  0 |  0  0

OPTIMAL (within feastol=9.1e-12, reltol=1.5e-10, abstol=1.5e-10).
Runtime: 0.000959 seconds.



In [6]:
#print(solution)
print("Optimal values of X:")
opt_x=solution['x']
print(opt_x)
Z=np.dot(c,opt_x)
print(Z)

Optimal values of X:
[  1.00000000e+00  -1.86759980e-11]
0.999999999963


### Problem 2:
Write a program to solve the following linear optimization problem using ECOS
$$Minimize: c^Tx$$
$$subject\ to:\ s <= Ax <= b$$
$$l <= x <= u$$
where $A, b, c, l, s, u$ are given as user specified input.<br>
Assume that the first line of the input has the format: n,m<br>
Here n is the number of variables and m the number of constraints (A matrix is thus mxn in size)<br>
The next line line is of the form:<br>
c1, c2, ..., cn (without line breaks)<br>
The next line line is of the form:<br>
s1, s2, ..., sm (without line breaks)<br>
The next line line is of the form:<br>
b1, b2, ..., bm (without line breaks)<br>
The next line line is of the form:<br>
l1, l2, ..., ln (without line breaks)<br>
The next line line is of the form:<br>
u1, u2, ..., un (without line breaks)<br>
Then we have m lines each containing the rows of A (elements separated by a comma). Your
program should print whether the inputs were read correctly, the status returned by ECOS
solver, and the optimal values of x.

In [7]:
##### Part 2 #####
X=input()
X=X.split(',')
n=int(X[0])
m=int(X[1])
A=[]

c=input()
c=c.split(',')
c=np.array(c,dtype=np.float32)
print("c:",end="")        
print(c) 

s=input()
s=s.split(',')
s=np.array(s,dtype=np.float32)
print("s:",end="")
print(s) 

b=input()
b=b.split(',')
b=np.array(b,dtype=np.float32)
print("b:",end="")
print(b)    

l=input()
l=l.split(',')
l=np.array(l,dtype=np.float32)
print("l:",end="")
print(l)   

u=input()
u=u.split(',')
u=np.array(u,dtype=np.float32)
print("u:",end="")
print(u) 

for i in range(m):
    a=input()
    a=a.split(',')
    A.append(a)
A=np.array(A,dtype=np.float32)
print("A:")
print(A)

3,5
1.0, 3.0, -2.0
c:[ 1.  3. -2.]
0.0, 1.0, 0.0, 0.0, 0.0
s:[ 0.  1.  0.  0.  0.]
15.0, 18.0, 20.0, 10.0, 10.0
b:[ 15.  18.  20.  10.  10.]
-50.0, -50.0, -50.0
l:[-50. -50. -50.]
50.0,  50.0,  50.0
u:[ 50.  50.  50.]
-1.0, 1.0, 1.0
3.0,  1.0, 2.0
1.0, 1.0, -1.0
-1.0, 1.0, -1.0
100.0, 2.0, -1.0
A:
[[  -1.    1.    1.]
 [   3.    1.    2.]
 [   1.    1.   -1.]
 [  -1.    1.   -1.]
 [ 100.    2.   -1.]]


In [8]:
G=np.zeros((2*m+2*n,n))
for i in range(m):
    for j in range(n):
        G[i][j]=-A[i][j]
        G[i+m][j]=A[i][j]
for i in range(m):
    for j in range(n):
        if i==j:
            G[i+2*m][j]=-1
            G[i+2*m+n][j]=1;
print(G) 
G=sparse.csc_matrix(G)

[[   1.   -1.   -1.]
 [  -3.   -1.   -2.]
 [  -1.   -1.    1.]
 [   1.   -1.    1.]
 [-100.   -2.    1.]
 [  -1.    1.    1.]
 [   3.    1.    2.]
 [   1.    1.   -1.]
 [  -1.    1.   -1.]
 [ 100.    2.   -1.]
 [  -1.    0.    0.]
 [   0.   -1.    0.]
 [   0.    0.   -1.]
 [   1.    0.    0.]
 [   0.    1.    0.]
 [   0.    0.    1.]]


In [9]:
h=np.concatenate((-s,b))
h=np.concatenate((h,-l))
h=np.concatenate((h,u))
print(h)

[ -0.  -1.  -0.  -0.  -0.  15.  18.  20.  10.  10.  50.  50.  50.  50.  50.
  50.]


In [10]:
dims2={'l':(2*m+2*n),'q':[],'e':0}
# solution2 = ecos.solve(c,G,h,dims2,G,h,max_iters=100000,verbose=True)
solution2 = ecos.solve(c,G,h,dims2,max_iters=100000,verbose=True)


ECOS 2.0.4 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  +1.743e+01  -1.215e+03  +1e+03  6e-03  3e-09  1e+00  7e+01    ---    ---    1  1  - |  -  - 
 1  +8.687e+00  -1.939e+02  +2e+02  1e-03  4e-08  6e-01  1e+01  0.8381  7e-03   0  0  0 |  0  0
 2  +1.441e+00  -1.226e+01  +1e+01  7e-05  5e-08  2e-01  9e-01  0.9438  1e-02   0  0  0 |  0  0
 3  +4.737e-01  -1.887e+00  +2e+00  1e-05  2e-08  3e-02  1e-01  0.8318  5e-03   0  0  0 |  0  0
 4  +3.890e-01  +6.674e-02  +3e-01  2e-06  5e-09  1e-02  2e-02  0.9269  7e-02   0  0  0 |  0  0
 5  +3.383e-01  +2.973e-01  +4e-02  2e-07  2e-09  2e-03  3e-03  0.8738  1e-03   0  0  0 |  0  0
 6  +3.339e-01  +3.312e-01  +3e-03  1e-08  1e-10  1e-04  2e-04  0.9660  3e-02   0  0  0 |  0  0
 7  +3.333e-01  +3.333e-01  +3e-05  2e-10  7e-12  1e-06  2e-06  0.9890  1e-04   0  0  0 |  0  0
 8  +3.333e-01  +3.333e-01  +3e-07  2e-12  1e-

In [11]:
print("Optimal values of X:")
opt_x2=solution2['x']
print(opt_x2)
Z=np.dot(c,opt_x2)
print(Z)

Optimal values of X:
[ -6.60853616e-12   3.33333334e-01   3.33333334e-01]
0.333333334059
